"""onboarding

Revision ID: 0ed7bdfa12bd
Revises: 10e736db18fa
Create Date: 2024-10-13 19:54:52.672317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed7bdfa12bd'
down_revision = '10e736db18fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Enum('MAN', 'WOMAN', name='gender_enum'), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_stage', sa.Enum('PENDING', 'COMPLETE', name='onboarding_stage_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('onboarding_stage')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
