"""add_search_logging

Revision ID: 280fe88a42c1
Revises: 0ed7bdfa12bd
Create Date: 2024-10-21 19:07:10.606716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280fe88a42c1'
down_revision = '0ed7bdfa12bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_click', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('search_query', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('referrer', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_click', schema=None) as batch_op:
        batch_op.drop_column('referrer')
        batch_op.drop_column('search_query')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
