"""apple_sign_in

Revision ID: 693211396d20
Revises: 1596f2fcc7af
Create Date: 2024-11-02 17:38:48.847911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693211396d20'
down_revision = '1596f2fcc7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_private_email', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_sub'), ['sub'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sub'))
        batch_op.drop_column('is_private_email')
        batch_op.drop_column('sub')

    # ### end Alembic commands ###
