"""add_referrer_to_wishlist

Revision ID: a23d5e5526d3
Revises: 280fe88a42c1
Create Date: 2024-10-21 19:09:19.786044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23d5e5526d3'
down_revision = '280fe88a42c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referrer', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.drop_column('referrer')

    # ### end Alembic commands ###
