"""empty message

Revision ID: b8d1a72a99e7
Revises: 412ce03894c2
Create Date: 2024-09-28 21:47:56.120502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d1a72a99e7'
down_revision = '412ce03894c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('landingPageUrl', sa.String(length=255), nullable=True),
    sa.Column('productId', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('productName', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('ratingCount', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('searchImage', sa.String(length=255), nullable=True),
    sa.Column('sizes', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('primaryColour', sa.String(length=50), nullable=True),
    sa.Column('additionalInfo', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('articleType', sa.String(length=255), nullable=True),
    sa.Column('subCategory', sa.String(length=255), nullable=True),
    sa.Column('masterCategory', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_productId'), ['productId'], unique=True)

    op.create_table('wishlist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_productId'))

    op.drop_table('product')
    # ### end Alembic commands ###
