"""empty message

Revision ID: f73a15052ef2
Revises: d9e3ba92180e
Create Date: 2024-10-09 20:58:18.018952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73a15052ef2'
down_revision = 'd9e3ba92180e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
